os:
  - linux
  - osx
python:
  - 2.7
services:
  - docker

sudo: false

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget --no-check https://repo.continuum.io/miniconda/Miniconda2-4.3.21-Linux-x86_64.sh  -O miniconda.sh ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh
    -O miniconda.sh; fi
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PREFIX="$HOME/miniconda"
  - export UDUNITS2_XML_PATH=$HOME/miniconda/share/udunits/udunits2.xml
  - export UVCDAT_ANONYMOUS_LOG=no
  - bash miniconda.sh -b -p $HOME/miniconda
  - conda config --set always_yes yes --set changeps1 no
  - conda update -y -q conda
  - conda install openssl=1.0.2d
  - conda install cdms2 -c cdat/label/nightly -c conda-forge -c cdat
  - conda install udunits2 -c cdat/label/nightly  -c conda-forge -c cdat
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then conda install gcc; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then conda install gcc; fi
  - source deactivate root
  - source activate root
install:
  - git clone https://github.com/PCMDI/cmip6-cmor-tables
  - ln -s cmip6-cmor-tables/Tables Tables
  - "./configure --prefix=$PREFIX --with-python --with-uuid=$PREFIX --with-udunits2=$PREFIX
    --with-netcdf=$PREFIX  --enable-verbose-test"
  - make install

script:
  - make test
  - for file in `ls -1 Test/test_python_CMIP6_CV*.py`; do echo $file; python $file; mystatus=$?; if [[ "$mystatus" != "0" ]]; then return ${mystatus}; fi; done

after_failure:
  - ulimit -a
  - free -m
  - find CMIP6/
  - df -kh ./
  - ls -lR
  - cat ~/build.sh

after_success:
  - if [ $TRAVIS_BRANCH == "master" -a "$TRAVIS_OS_NAME" = "osx" ]; then bash scripts/conda_upload.sh ${TRAVIS_BRANCH} ; fi
  - if [ $TRAVIS_BRANCH == "fix_travis_upload" -a "$TRAVIS_OS_NAME" = "linux" ]; then docker run -v `pwd`:/travis_home -e CONDA_UPLOAD_TOKEN=${CONDA_UPLOAD_TOKEN} -a STDOUT -a STDERR centos:6.8 /travis_home/scripts/conda_upload.sh ${TRAVIS_BRANCH} ; fi
